version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  xiq-st2-openfaas:
    lang: python3
    handler: ./xiq-st2-openfaas
    image: tknv/xiq-st2-openfaas:latest
    enviroment:
      write_debug: true
      combine_output: false
    environment_file:
    - env.yml